
export type State = {
  name: string;
  code: string;
};

export type Country = {
  name: string;
  code: string;
  phoneCode: string;
  states: State[] | null;
};

export const countries: Country[] = [
  {
    name: 'United States',
    code: 'US',
    phoneCode: '+1',
    states: [
      { name: 'Alabama', code: 'AL' },
      { name: 'Alaska', code: 'AK' },
      { name: 'Arizona', code: 'AZ' },
      { name: 'Arkansas', code: 'AR' },
      { name: 'California', code: 'CA' },
      { name: 'Colorado', code: 'CO' },
      { name: 'Connecticut', code: 'CT' },
      { name: 'Delaware', code: 'DE' },
      { name: 'Florida', code: 'FL' },
      { name: 'Georgia', code: 'GA' },
      { name: 'Hawaii', code: 'HI' },
      { name: 'Idaho', code: 'ID' },
      { name: 'Illinois', code: 'IL' },
      { name: 'Indiana', code: 'IN' },
      { name: 'Iowa', code: 'IA' },
      { name: 'Kansas', code: 'KS' },
      { name: 'Kentucky', code: 'KY' },
      { name: 'Louisiana', code: 'LA' },
      { name: 'Maine', code: 'ME' },
      { name: 'Maryland', code: 'MD' },
      { name: 'Massachusetts', code: 'MA' },
      { name: 'Michigan', code: 'MI' },
      { name: 'Minnesota', code: 'MN' },
      { name: 'Mississippi', code: 'MS' },
      { name: 'Missouri', code: 'MO' },
      { name: 'Montana', code: 'MT' },
      { name: 'Nebraska', code: 'NE' },
      { name: 'Nevada', code: 'NV' },
      { name: 'New Hampshire', code: 'NH' },
      { name: 'New Jersey', code: 'NJ' },
      { name: 'New Mexico', code: 'NM' },
      { name: 'New York', code: 'NY' },
      { name: 'North Carolina', code: 'NC' },
      { name: 'North Dakota', code: 'ND' },
      { name: 'Ohio', code: 'OH' },
      { name: 'Oklahoma', code: 'OK' },
      { name: 'Oregon', code: 'OR' },
      { name: 'Pennsylvania', code: 'PA' },
      { name: 'Rhode Island', code: 'RI' },
      { name: 'South Carolina', code: 'SC' },
      { name: 'South Dakota', code: 'SD' },
      { name: 'Tennessee', code: 'TN' },
      { name: 'Texas', code: 'TX' },
      { name: 'Utah', code: 'UT' },
      { name: 'Vermont', code: 'VT' },
      { name: 'Virginia', code: 'VA' },
      { name: 'Washington', code: 'WA' },
      { name: 'West Virginia', code: 'WV' },
      { name: 'Wisconsin', code: 'WI' },
      { name: 'Wyoming', code: 'WY' },
    ],
  },
  {
    name: 'Canada',
    code: 'CA',
    phoneCode: '+1',
    states: [
        { name: 'Alberta', code: 'AB' },
        { name: 'British Columbia', code: 'BC' },
        { name: 'Manitoba', code: 'MB' },
        { name: 'New Brunswick', code: 'NB' },
        { name: 'Newfoundland and Labrador', code: 'NL' },
        { name: 'Nova Scotia', code: 'NS' },
        { name: 'Ontario', code: 'ON' },
        { name: 'Prince Edward Island', code: 'PE' },
        { name: 'Quebec', code: 'QC' },
        { name: 'Saskatchewan', code: 'SK' },
    ],
  },
  { name: 'Afghanistan', code: 'AF', phoneCode: '+93', states: null },
  { name: 'Albania', code: 'AL', phoneCode: '+355', states: null },
  { name: 'Algeria', code: 'DZ', phoneCode: '+213', states: null },
  { name: 'Andorra', code: 'AD', phoneCode: '+376', states: null },
  { name: 'Angola', code: 'AO', phoneCode: '+244', states: null },
  { name: 'Argentina', code: 'AR', phoneCode: '+54', states: null },
  { name: 'Armenia', code: 'AM', phoneCode: '+374', states: null },
  { name: 'Australia', code: 'AU', phoneCode: '+61', states: null },
  { name: 'Austria', code: 'AT', phoneCode: '+43', states: null },
  { name: 'Azerbaijan', code: 'AZ', phoneCode: '+994', states: null },
  { name: 'Bahamas', code: 'BS', phoneCode: '+1-242', states: null },
  { name: 'Bahrain', code: 'BH', phoneCode: '+973', states: null },
  { name: 'Bangladesh', code: 'BD', phoneCode: '+880', states: null },
  { name: 'Barbados', code: 'BB', phoneCode: '+1-246', states: null },
  { name: 'Belarus', code: 'BY', phoneCode: '+375', states: null },
  { name: 'Belgium', code: 'BE', phoneCode: '+32', states: null },
  { name: 'Belize', code: 'BZ', phoneCode: '+501', states: null },
  { name: 'Benin', code: 'BJ', phoneCode: '+229', states: null },
  { name: 'Bhutan', code: 'BT', phoneCode: '+975', states: null },
  { name: 'Bolivia', code: 'BO', phoneCode: '+591', states: null },
  { name: 'Bosnia and Herzegovina', code: 'BA', phoneCode: '+387', states: null },
  { name: 'Botswana', code: 'BW', phoneCode: '+267', states: null },
  { name: 'Brazil', code: 'BR', phoneCode: '+55', states: null },
  { name: 'Brunei', code: 'BN', phoneCode: '+673', states: null },
  { name: 'Bulgaria', code: 'BG', phoneCode: '+359', states: null },
  { name: 'Burkina Faso', code: 'BF', phoneCode: '+226', states: null },
  { name: 'Burundi', code: 'BI', phoneCode: '+257', states: null },
  { name: 'Cambodia', code: 'KH', phoneCode: '+855', states: null },
  { name: 'Cameroon', code: 'CM', phoneCode: '+237', states: null },
  { name: 'Cape Verde', code: 'CV', phoneCode: '+238', states: null },
  { name: 'Central African Republic', code: 'CF', phoneCode: '+236', states: null },
  { name: 'Chad', code: 'TD', phoneCode: '+235', states: null },
  { name: 'Chile', code: 'CL', phoneCode: '+56', states: null },
  { name: 'China', code: 'CN', phoneCode: '+86', states: null },
  { name: 'Colombia', code: 'CO', phoneCode: '+57', states: null },
  { name: 'Comoros', code: 'KM', phoneCode: '+269', states: null },
  { name: 'Congo (Brazzaville)', code: 'CG', phoneCode: '+242', states: null },
  { name: 'Congo (Kinshasa)', code: 'CD', phoneCode: '+243', states: null },
  { name: 'Costa Rica', code: 'CR', phoneCode: '+506', states: null },
  { name: 'Croatia', code: 'HR', phoneCode: '+385', states: null },
  { name: 'Cuba', code: 'CU', phoneCode: '+53', states: null },
  { name: 'Cyprus', code: 'CY', phoneCode: '+357', states: null },
  { name: 'Czech Republic', code: 'CZ', phoneCode: '+420', states: null },
  { name: 'Denmark', code: 'DK', phoneCode: '+45', states: null },
  { name: 'Djibouti', code: 'DJ', phoneCode: '+253', states: null },
  { name: 'Dominica', code: 'DM', phoneCode: '+1-767', states: null },
  { name: 'Dominican Republic', code: 'DO', phoneCode: '+1-809', states: null },
  { name: 'Ecuador', code: 'EC', phoneCode: '+593', states: null },
  { name: 'Egypt', code: 'EG', phoneCode: '+20', states: null },
  { name: 'El Salvador', code: 'SV', phoneCode: '+503', states: null },
  { name: 'Equatorial Guinea', code: 'GQ', phoneCode: '+240', states: null },
  { name: 'Eritrea', code: 'ER', phoneCode: '+291', states: null },
  { name: 'Estonia', code: 'EE', phoneCode: '+372', states: null },
  { name: 'Eswatini', code: 'SZ', phoneCode: '+268', states: null },
  { name: 'Ethiopia', code: 'ET', phoneCode: '+251', states: null },
  { name: 'Fiji', code: 'FJ', phoneCode: '+679', states: null },
  { name: 'Finland', code: 'FI', phoneCode: '+358', states: null },
  { name: 'France', code: 'FR', phoneCode: '+33', states: null },
  { name: 'Gabon', code: 'GA', phoneCode: '+241', states: null },
  { name: 'Gambia', code: 'GM', phoneCode: '+220', states: null },
  { name: 'Georgia', code: 'GE', phoneCode: '+995', states: null },
  { name: 'Germany', code: 'DE', phoneCode: '+49', states: null },
  { name: 'Ghana', code: 'GH', phoneCode: '+233', states: null },
  { name: 'Greece', code: 'GR', phoneCode: '+30', states: null },
  { name: 'Grenada', code: 'GD', phoneCode: '+1-473', states: null },
  { name: 'Guatemala', code: 'GT', phoneCode: '+502', states: null },
  { name: 'Guinea', code: 'GN', phoneCode: '+224', states: null },
  { name: 'Guinea-Bissau', code: 'GW', phoneCode: '+245', states: null },
  { name: 'Guyana', code: 'GY', phoneCode: '+592', states: null },
  { name: 'Haiti', code: 'HT', phoneCode: '+509', states: null },
  { name: 'Honduras', code: 'HN', phoneCode: '+504', states: null },
  { name: 'Hungary', code: 'HU', phoneCode: '+36', states: null },
  { name: 'Iceland', code: 'IS', phoneCode: '+354', states: null },
  { name: 'India', code: 'IN', phoneCode: '+91', states: null },
  { name: 'Indonesia', code: 'ID', phoneCode: '+62', states: null },
  { name: 'Iran', code: 'IR', phoneCode: '+98', states: null },
  { name: 'Iraq', code: 'IQ', phoneCode: '+964', states: null },
  { name: 'Ireland', code: 'IE', phoneCode: '+353', states: null },
  { name: 'Israel', code: 'IL', phoneCode: '+972', states: null },
  { name: 'Italy', code: 'IT', phoneCode: '+39', states: null },
  { name: 'Jamaica', code: 'JM', phoneCode: '+1-876', states: null },
  { name: 'Japan', code: 'JP', phoneCode: '+81', states: null },
  { name: 'Jordan', code: 'JO', phoneCode: '+962', states: null },
  { name: 'Kazakhstan', code: 'KZ', phoneCode: '+7', states: null },
  { name: 'Kenya', code: 'KE', phoneCode: '+254', states: null },
  { name: 'Kiribati', code: 'KI', phoneCode: '+686', states: null },
  { name: 'Kuwait', code: 'KW', phoneCode: '+965', states: null },
  { name: 'Kyrgyzstan', code: 'KG', phoneCode: '+996', states: null },
  { name: 'Laos', code: 'LA', phoneCode: '+856', states: null },
  { name: 'Latvia', code: 'LV', phoneCode: '+371', states: null },
  { name: 'Lebanon', code: 'LB', phoneCode: '+961', states: null },
  { name: 'Lesotho', code: 'LS', phoneCode: '+266', states: null },
  { name: 'Liberia', code: 'LR', phoneCode: '+231', states: null },
  { name: 'Libya', code: 'LY', phoneCode: '+218', states: null },
  { name: 'Liechtenstein', code: 'LI', phoneCode: '+423', states: null },
  { name: 'Lithuania', code: 'LT', phoneCode: '+370', states: null },
  { name: 'Luxembourg', code: 'LU', phoneCode: '+352', states: null },
  { name: 'Madagascar', code: 'MG', phoneCode: '+261', states: null },
  { name: 'Malawi', code: 'MW', phoneCode: '+265', states: null },
  { name: 'Malaysia', code: 'MY', phoneCode: '+60', states: null },
  { name: 'Maldives', code: 'MV', phoneCode: '+960', states: null },
  { name: 'Mali', code: 'ML', phoneCode: '+223', states: null },
  { name: 'Malta', code: 'MT', phoneCode: '+356', states: null },
  { name: 'Marshall Islands', code: 'MH', phoneCode: '+692', states: null },
  { name: 'Mauritania', code: 'MR', phoneCode: '+222', states: null },
  { name: 'Mauritius', code: 'MU', phoneCode: '+230', states: null },
  { name: 'Mexico', code: 'MX', phoneCode: '+52', states: null },
  { name: 'Micronesia', code: 'FM', phoneCode: '+691', states: null },
  { name: 'Moldova', code: 'MD', phoneCode: '+373', states: null },
  { name: 'Monaco', code: 'MC', phoneCode: '+377', states: null },
  { name: 'Mongolia', code: 'MN', phoneCode: '+976', states: null },
  { name: 'Montenegro', code: 'ME', phoneCode: '+382', states: null },
  { name: 'Morocco', code: 'MA', phoneCode: '+212', states: null },
  { name: 'Mozambique', code: 'MZ', phoneCode: '+258', states: null },
  { name: 'Myanmar', code: 'MM', phoneCode: '+95', states: null },
  { name: 'Namibia', code: 'NA', phoneCode: '+264', states: null },
  { name: 'Nauru', code: 'NR', phoneCode: '+674', states: null },
  { name: 'Nepal', code: 'NP', phoneCode: '+977', states: null },
  { name: 'Netherlands', code: 'NL', phoneCode: '+31', states: null },
  { name: 'New Zealand', code: 'NZ', phoneCode: '+64', states: null },
  { name: 'Nicaragua', code: 'NI', phoneCode: '+505', states: null },
  { name: 'Niger', code: 'NE', phoneCode: '+227', states: null },
  { name: 'Nigeria', code: 'NG', phoneCode: '+234', states: null },
  { name: 'North Korea', code: 'KP', phoneCode: '+850', states: null },
  { name: 'North Macedonia', code: 'MK', phoneCode: '+389', states: null },
  { name: 'Norway', code: 'NO', phoneCode: '+47', states: null },
  { name: 'Oman', code: 'OM', phoneCode: '+968', states: null },
  { name: 'Pakistan', code: 'PK', phoneCode: '+92', states: null },
  { name: 'Palau', code: 'PW', phoneCode: '+680', states: null },
  { name: 'Panama', code: 'PA', phoneCode: '+507', states: null },
  { name: 'Papua New Guinea', code: 'PG', phoneCode: '+675', states: null },
  { name: 'Paraguay', code: 'PY', phoneCode: '+595', states: null },
  { name: 'Peru', code: 'PE', phoneCode: '+51', states: null },
  { name: 'Philippines', code: 'PH', phoneCode: '+63', states: null },
  { name: 'Poland', code: 'PL', phoneCode: '+48', states: null },
  { name: 'Portugal', code: 'PT', phoneCode: '+351', states: null },
  { name: 'Qatar', code: 'QA', phoneCode: '+974', states: null },
  { name: 'Romania', code: 'RO', phoneCode: '+40', states: null },
  { name: 'Russia', code: 'RU', phoneCode: '+7', states: null },
  { name: 'Rwanda', code: 'RW', phoneCode: '+250', states: null },
  { name: 'Saint Kitts and Nevis', code: 'KN', phoneCode: '+1-869', states: null },
  { name: 'Saint Lucia', code: 'LC', phoneCode: '+1-758', states: null },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', phoneCode: '+1-784', states: null },
  { name: 'Samoa', code: 'WS', phoneCode: '+685', states: null },
  { name: 'San Marino', code: 'SM', phoneCode: '+378', states: null },
  { name: 'Sao Tome and Principe', code: 'ST', phoneCode: '+239', states: null },
  { name: 'Saudi Arabia', code: 'SA', phoneCode: '+966', states: null },
  { name: 'Senegal', code: 'SN', phoneCode: '+221', states: null },
  { name: 'Serbia', code: 'RS', phoneCode: '+381', states: null },
  { name: 'Seychelles', code: 'SC', phoneCode: '+248', states: null },
  { name: 'Sierra Leone', code: 'SL', phoneCode: '+232', states: null },
  { name: 'Singapore', code: 'SG', phoneCode: '+65', states: null },
  { name: 'Slovakia', code: 'SK', phoneCode: '+421', states: null },
  { name: 'Slovenia', code: 'SI', phoneCode: '+386', states: null },
  { name: 'Solomon Islands', code: 'SB', phoneCode: '+677', states: null },
  { name: 'Somalia', code: 'SO', phoneCode: '+252', states: null },
  { name: 'South Africa', code: 'ZA', phoneCode: '+27', states: null },
  { name: 'South Korea', code: 'KR', phoneCode: '+82', states: null },
  { name: 'South Sudan', code: 'SS', phoneCode: '+211', states: null },
  { name: 'Spain', code: 'ES', phoneCode: '+34', states: null },
  { name: 'Sri Lanka', code: 'LK', phoneCode: '+94', states: null },
  { name: 'Sudan', code: 'SD', phoneCode: '+249', states: null },
  { name: 'Suriname', code: 'SR', phoneCode: '+597', states: null },
  { name: 'Sweden', code: 'SE', phoneCode: '+46', states: null },
  { name: 'Switzerland', code: 'CH', phoneCode: '+41', states: null },
  { name: 'Syria', code: 'SY', phoneCode: '+963', states: null },
  { name: 'Taiwan', code: 'TW', phoneCode: '+886', states: null },
  { name: 'Tajikistan', code: 'TJ', phoneCode: '+992', states: null },
  { name: 'Tanzania', code: 'TZ', phoneCode: '+255', states: null },
  { name: 'Thailand', code: 'TH', phoneCode: '+66', states: null },
  { name: 'Timor-Leste', code: 'TL', phoneCode: '+670', states: null },
  { name: 'Togo', code: 'TG', phoneCode: '+228', states: null },
  { name: 'Tonga', code: 'TO', phoneCode: '+676', states: null },
  { name: 'Trinidad and Tobago', code: 'TT', phoneCode: '+1-868', states: null },
  { name: 'Tunisia', code: 'TN', phoneCode: '+216', states: null },
  { name: 'Turkey', code: 'TR', phoneCode: '+90', states: null },
  { name: 'Turkmenistan', code: 'TM', phoneCode: '+993', states: null },
  { name: 'Tuvalu', code: 'TV', phoneCode: '+688', states: null },
  { name: 'Uganda', code: 'UG', phoneCode: '+256', states: null },
  { name: 'Ukraine', code: 'UA', phoneCode: '+380', states: null },
  { name: 'United Arab Emirates', code: 'AE', phoneCode: '+971', states: null },
  { name: 'United Kingdom', code: 'GB', phoneCode: '+44', states: null },
  { name: 'Uruguay', code: 'UY', phoneCode: '+598', states: null },
  { name: 'Uzbekistan', code: 'UZ', phoneCode: '+998', states: null },
  { name: 'Vanuatu', code: 'VU', phoneCode: '+678', states: null },
  { name: 'Venezuela', code: 'VE', phoneCode: '+58', states: null },
  { name: 'Vietnam', code: 'VN', phoneCode: '+84', states: null },
  { name: 'Yemen', code: 'YE', phoneCode: '+967', states: null },
  { name: 'Zambia', code: 'ZM', phoneCode: '+260', states: null },
  { name: 'Zimbabwe', code: 'ZW', phoneCode: '+263', states: null },
];
