import { type AdminUser } from './user-dialog';

export const initialUsers: AdminUser[] = [
  {
    id: 'usr_0',
    name: 'Robert Snalo',
    email: 'robertsnalo@digitaladdress.com',
    phone: '+1-555-000-0000',
    password: 'password',
    role: 'super-admin',
    status: 'Active',
    permissions: ['dashboard', 'user-management', 'b2b-clients', 'address-audit', 'monetization', 'incident-response', 'platform-settings'],
  },
  {
    id: 'usr_1',
    name: 'Nicholas C.',
    email: 'nicholas@digitaladdress.com',
    phone: '+1-555-111-1111',
    password: 'password',
    role: 'super-admin',
    status: 'Active',
    permissions: ['dashboard', 'user-management', 'b2b-clients', 'address-audit', 'monetization', 'incident-response', 'platform-settings'],
  },
  {
    id: 'usr_2',
    name: 'Alice Johnson',
    email: 'alice.j@digitaladdress.com',
    phone: '+1-555-222-2222',
    password: 'password',
    role: 'admin-assistant',
    status: 'Active',
    permissions: ['dashboard', 'b2b-clients', 'address-audit'],
  },
  {
    id: 'usr_3',
    name: 'Bob Williams',
    email: 'bob.w@digitaladdress.com',
    phone: '+1-555-333-3333',
    password: 'password',
    role: 'compliance-officer',
    status: 'Pending Approval',
    permissions: ['address-audit'],
  },
  {
    id: 'usr_4',
    name: 'Charlie Brown',
    email: 'charlie.b@digitaladdress.com',
    phone: '+1-555-444-4444',
    password: 'password',
    role: 'support-agent',
    status: 'Inactive',
    permissions: [],
  },
   {
    id: 'usr_5',
    name: 'Diana Prince',
    email: 'diana.p@digitaladdress.com',
    phone: '+1-555-555-5555',
    password: 'password',
    role: 'support-agent',
    status: 'Suspended',
    permissions: [],
  },
];
